### ISSUE TITLE
Split each model to its own substack?

### ISSUE THREAD

**Issue by oyyblin** [kcwinner/cdk-appsync-transformer#333]
Amplify does this by default. With cdk-appsync-transformer, all appsync resources are aggregated into a single cloudformation stack. My template just hit the 1MB template file size hard cap, and cannot be updated anymore :(

Anyone knows how can we deal with this? Maybe we can make it generates multiple stacks instead of a single one?

**Comment by computationalcore** [comment]
@kcwinner I'm facing the same issue. As @ZhongtianWang mentioned I saw that at [some point ](https://github.com/aws-amplify/amplify-cli/issues/185) Amplify generates nested stacks for API instead of only one.

Do you think is this something complex to solve? Cause this make the library less useful for midsize+ projects.

I will try to help with that.

**Comment by kcwinner** [comment]
I think the best option here is to make the upgrade to the new Amplify data models a breaking change and make multiple stacks. I believe if I leave the tables in the same place people could migrate easily. Otherwise, if I move tables then people would have to migrate data when new tables are created

**Comment by KevinCGH** [comment]
any updates to this issue? I'm facing the same problem that I can't add tables anymore.

**Comment by kcwinner** [comment]
I'm restarting my work on the v2 migration. This will cause some breaking changes so it will be pushed into the v2 release.

**Comment by kcwinner** [comment]
Would you all be interested in testing an alpha with breaking changes? All CDK v2 and separate stacks

**Comment by computationalcore** [comment]
> Would you all be interested in testing an alpha with breaking changes? All CDK v2 and separate stacks

@kcwinner I would like, thanks!
