### ISSUE TITLE
Update to CDK v2.x

### ISSUE THREAD

**Issue by computationalcore** [kcwinner/cdk-appsync-transformer#346]
@kcwinner when do you plan to upgrade the project to CDK 2.x? Please let me know if I can help with anything. Feel free to ping me if you want some help with this, if you have any architectural patterns you want to follow, we can coordinate this before I actually get started.

Best regards,

Vin Busquet

**Comment by kcwinner** [comment]
I've started work on this. However, appsync is in alpha in cdkv2. I've hit a snag with lambda data sources. Will update as I progress.

**Comment by kcwinner** [comment]
@computationalcore you can try it out at `v2.0.0-alpha.0` or use `cdk-appsync-transformer@next`. I created a sample cdk app and tested a few things. But I don't have a live project right now to test against thoroughly.

**Comment by computationalcore** [comment]
> @computationalcore you can try it out at `v2.0.0-alpha.0` or use `cdk-appsync-transformer@next`. I created a sample cdk app and tested a few things. But I don't have a live project right now to test against thoroughly.

Got it. Thanks for the feedback and update. I can try later. Also I noticed what you mentioned later, that CDK  2 appsync support is still alpha for L2 constructs, only the L1 constructs are stable (since they are a direct map to Cloudformation).

Another question, have you checked out the new amplify  [data modeling directives](https://docs.amplify.aws/cli/graphql/data-modeling/) that replaces @connection directive? 

Do you think it's an interesting/feasible thing to add support? Again, if you want you can count on me for some cooperation, I just want to avoid blind contributions.

Best Regards,

Vin Busquet

**Comment by kcwinner** [comment]
@computationalcore I've been looking at supporting the new directives. This is looking more and more like a breaking change to support it. I've got a basic setup reading the new directives into the transformer, but the way it outputs uses CDK natively now instead of their cloudformation setup. 

So, this library may make less sense the way it works now. I see a few paths:
- Convert the new amplify outputs to exactly what we have
- Output the CDK stacks from Amplify and let the owner determine what to do (would address #333 as well)
- Some combination of the two
- ???

**Comment by computationalcore** [comment]
@kcwinner got it. It seems to me that a combination of the two is the ideal, It seems to me that a combination of the two is ideal, but for compatibility reasons and perhaps narrowing the scope, I would vote to convert the new amplify outputs to exactly what we have (I'm also not sure if that's the simplest path).

**Comment by tajinder-gill** [comment]
Any update on the progress of this given CDK v1.x is officially in maintenance now too.
