### ISSUE TITLE
Semver on CDK support

### ISSUE THREAD

**Issue by mbonig** [kcwinner/cdk-appsync-transformer#46]
Right now this library must be used with CDK 1.70.0. Do you see any issue with updating this to ^1.70.0?

**Comment by kcwinner** [comment]
@mbonig No issues in particular. I believe most of the required libraries are no longer experimental except for AppSync. Cognito UserPools are stable as well. I have run into various issues when a construct supports ^1.xx.x instead of being pinned. 

Example: 
I wrote [this construct](https://github.com/kcwinner/cdk-bucket-deployment-expirator#readme) and it allows ^1.74.0. However, if your project requires 1.75.0 and 1.76.0 is out, you have to update. That or I made a mistake somewhere along the way...

**Comment by mbonig** [comment]
> However, if your project requires 1.75.0 and 1.76.0 is out, if you install the construct supporting ^ you have to update. 

Not sure I understand. What has to be updated?

**Comment by kcwinner** [comment]
Installing `construct x` supporting ^1.74.0 into `project y` using 1.75.0 ended up installing 1.76.0 for me and/or failing

```
const { AwsCdkTypeScriptApp } = require('projen');

const project = new AwsCdkTypeScriptApp({
  name: 'cdktest',
  cdkVersion: '1.74.0',
  cdkVersionPinning: true,
  cdkDependencies: [
    '@aws-cdk/aws-s3',
    '@aws-cdk/aws-s3-deployment',
    '@aws-cdk/core'
  ],
  deps: [
    'cdk-bucket-deployment-expirator'
  ]
});

project.synth();
```

When running `pj` I get:
```
Error: Command failed: yarn install --check-files
warning " > @aws-cdk/assert@1.74.0" has unmet peer dependency "constructs@^3.2.0".
warning " > @aws-cdk/core@1.74.0" has unmet peer dependency "@aws-cdk/cloud-assembly-schema@1.74.0".
...
...
warning "cdk-bucket-deployment-expirator > @aws-cdk/aws-s3-deployment > @aws-cdk/aws-cloudfront > @aws-cdk/aws-certificatemanager > @aws-cdk/aws-route53@1.76.0" has unmet peer dependency "@aws-cdk/cloud-assembly-schema@1.76.0".
error An unexpected error occurred: "expected hoisted manifest for \"cdk-bucket-deployment-expirator#@aws-cdk/aws-s3#@aws-cdk/aws-kms\"".
```

**Comment by mbonig** [comment]
Gotcha. I'll try to dig into it and see if there is a way to resolve the hoisting issue.

**Comment by kcwinner** [comment]
@mbonig Given our conversation in the slack, I've release 1.77.0 supporting cdk version ^1.77.0
I individually released 1.70 - 1.76 as a backup

**Comment by mbonig** [comment]
Thanks! I appreciate it!

**Comment by gourav-singhal** [comment]
@gourav-singhal
